### PR TITLE
Agrego signos a los ingresos y egresos

### PR DESCRIPTION
**Pull request by Matute1998**

### CODE REVIEW

**Comment by Matute1998** [comment]
File               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-------------------|---------|----------|---------|---------|----------------------
All files          |   86.81 |    71.11 |   68.57 |   87.86 |
 client/js         |   70.59 |      100 |      25 |   66.67 |
  utils.js         |   70.59 |      100 |      25 |   66.67 | 20-47
 server            |    91.3 |       60 |   83.33 |   93.33 |
  db.js            |     100 |       50 |     100 |     100 | 9-10
  index.js         |      90 |    63.64 |   83.33 |   92.31 | 32,55,71
 server/models     |     100 |    72.22 |     100 |     100 |
  index.js         |     100 |      100 |     100 |     100 |
  movement.js      |     100 |    72.22 |     100 |     100 | 70,72,74,90,94
  movementType.js  |     100 |      100 |     100 |     100 |
 server/routes     |      75 |    83.33 |   57.14 |      75 |
  movement.js      |   75.86 |    83.33 |   66.67 |   75.86 | 30-31,46-47,65,81-83
  view.js          |   71.43 |      100 |       0 |   71.43 | 6,10
 server/utils      |   85.71 |       50 |      50 |     100 |
  env.js           |     100 |       50 |     100 |     100 | 2
  nunjucks.js      |   83.33 |      100 |      50 |     100 |
 tests             |     100 |      100 |     100 |     100 |
  nunjucks-util.js |     100 |      100 |     100 |     100 |

**Review by aguszanetta — APPROVED** [review]
Está bien, pero los próximos PRs vamos a hacerlos más atómicos.

**Review by fTessadro — APPROVED** [review]
funciona

**Review by drt0x — APPROVED** [review]
approve , perdon por la tardanza

**Pull request merged**
